### ISSUE TITLE
add a way to remove animation

### ISSUE THREAD

**Issue by benzen** [davidchin/react-input-range#32]
Hi,
the animation is nice and all. 
But what if I'd like to remove/disable the animation ?

Is there a way to do it atm ?

Regards

**Comment by jdelafon** [comment]
The animation is slow and annoying IMO, I'd also love it without a delay.

**Comment by fetis** [comment]
It's possible to remove animation via SCSS set this
```
$InputRange-sliderContainer-transition: none;
$inputRange-track-transition: none;
```

**Comment by oyeanuj** [comment]
It would be sweet to make it configurable thru a prop - both enabling/disabling it but also the currently hardcoded duration 0.3s for the ease.

cc: @davidchin

**Comment by renaudtertrais** [comment]
This works for me:

```scss
.input-range__track,
.input-range__container,
.input-range__slider {
  transition: none;
}
```

**Comment by renaudtertrais** [comment]
This works for me:

```scss
.input-range__track,
.input-range__slider-container {
  transition: none;
}
```
